name: macos-precompile

on:
  push:
    tags:
      - '*-dev'
      - '*-prod'
      - '*-dev-macos'

jobs:
  mix_test:
    runs-on: macos-11
    env:
      MIX_ENV: dev
      NIF_VERSION: 0.1.0
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              arch: x86_64
          - pair:
              arch: arm64

    steps:
      - uses: actions/checkout@v2

      - name: Install Erlang and Elixir
        run: |
          brew install erlang
          brew install elixir
          mix local.hex --force
          mix local.rebar --force

      - name: Create precompiled library
        run: |
          if [ "${{ matrix.pair.arch }}" = "arm64" ]; then
            export CMAKE_SNAPPY_OPTIONS="-D CMAKE_OSX_ARCHITECTURES=arm64"
          fi

          mix deps.get
          mix compile
          export PKG_NAME=snappy-darwin-${{ matrix.pair.arch }}-${NIF_VERSION}
          mkdir -p "${PKG_NAME}"
          cp -a _build/${MIX_ENV}/lib/snappy/priv "${PKG_NAME}"
          tar -czf "${PKG_NAME}.tar.gz" "${PKG_NAME}"
          rm -rf "${PKG_NAME}"
          ls -lah "${PKG_NAME}.tar.gz"
          mkdir -p artifacts
          mv "${PKG_NAME}.tar.gz" artifacts

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: 0.1.0
          files: artifacts/*.tar.gz
