name: windows-x86_64

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
      - 'LICENSE*'
      - 'examples/**'
      - 'Makefile'
      - 'cc_toolchain/**'
      - '.github/FUNDING.yml'
      - '.github/workflows/linux-*.yml'
      - '.github/workflows/macos-*.yml'
      - '.github/workflows/test-*.yml'
      - '.github/workflows/windows-precompile.yml'
  push:
    branches:
      - main
      - test-*
    paths-ignore:
      - '**/README.md'
      - 'LICENSE*'
      - 'examples/**'
      - 'Makefile'
      - 'cc_toolchain/**'
      - '.github/FUNDING.yml'
      - '.github/workflows/linux-*.yml'
      - '.github/workflows/macos-*.yml'
      - '.github/workflows/test-*.yml'
      - '.github/workflows/windows-precompile.yml'
  workflow_dispatch:

jobs:
  mix_test:
    runs-on: windows-latest
    env:
      MIX_ENV: test
      MAKE: nmake

    steps:
      - uses: actions/checkout@v2
      
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.3
          elixir-version: 1.13.3

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Mix Compile
        run: |
          mix deps.get
          Remove-Item Makefile
          mix compile

      - name: Mix Test
        run: |
          mix test --cover
